In [1]:
import pandas as pd
import os

In [2]:
base_dir = os.path.abspath('../../_data')
data_dir = os.path.join(base_dir, 'cat-in-the-dat-ii')
train_fp = os.path.join(data_dir, 'train.csv')
test_fp = os.path.join(data_dir, 'test.csv')

In [5]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
data = pd.read_csv(train_fp)

In [6]:
data.head()

   id  bin_0  bin_1  bin_2 bin_3 bin_4 nom_0      nom_1    nom_2       nom_3     nom_4      nom_5      nom_6      nom_7      nom_8      nom_9  ord_0        ord_1     ord_2 ord_3 ord_4 ord_5  day  month  target
0   0    0.0    0.0    0.0     F     N   Red  Trapezoid  Hamster      Russia   Bassoon  de4c57ee2  a64bc7ddf  598080a91  0256c7a4b  02e7c8990    3.0  Contributor       Hot     c     U    Pw  6.0    3.0       0
1   1    1.0    1.0    0.0     F     Y   Red       Star  Axolotl         NaN  Theremin  2bb3c3e5c  3a3a936e8  1dddb8473  52ead350c  f37df64af    3.0  Grandmaster      Warm     e     X    pE  7.0    7.0       0
2   2    0.0    1.0    0.0     F     N   Red        NaN  Hamster      Canada   Bassoon  b574c9841  708248125  5ddc9a726  745b909d1        NaN    3.0          NaN  Freezing     n     P    eN  5.0    9.0       0
3   3    NaN    0.0    0.0     F     N   Red     Circle  Hamster     Finland  Theremin  673bdf1f6  23edb8da3  3a33ef960  bdaa56dd1  f9d456e57    1.0       Novice  Lava Hot     a     C   NaN  3.0    3.0       0
4   4    0.0    NaN    0.0     T     N   Red   Triangle  Hamster  Costa Rica       NaN  777d1ac2c  3a7975e46  bc9cc2a94        NaN  c5361037c    3.0  Grandmaster      Cold     h     C    OZ  5.0   12.0       0

In [14]:
data.ord_5.value_counts()

Fl    10562
DN     9527
Sz     8654
RV     5648
oJ     5596
PS     5447
vq     5443
WW     5385
XC     5383
AG     5364
GZ     5348
be     5313
DR     5292
vx     5237
tn     5231
lS     5229
hG     5224
mo     5174
Ib     5129
mD     5120
TL     5112
TZ     5092
Hk     5033
Nh     4986
YJ     4968
rl     4961
RD     4949
gc     4926
uQ     4923
pB     4852
Mg     4831
MV     4826
rM     4792
oU     4753
rA     4738
JQ     4717
Dj     4686
DI     4682
UV     4654
yE     4623
fV     4582
ep     4572
Pw     4568
OZ     4565
XM     4554
Ey     4520
oh     4512
ly     4489
AU     4487
NS     4475
sf     4458
rg     4437
sc     4427
wa     4417
qP     4362
Bx     4349
kT     4348
pE     4293
xG     4290
dh     4288
US     4281
DT     4224
hT     4210
jf     4193
th     4150
qN     4133
EC     4103
nj     4099
HK     4072
oI     3972
aE     3954
Pk     3954
hx     3931
IS     3930
XR     3888
nS     3792
LY     3790
mi     3712
AI     3677
Rz     3657
Lo     3633
nn     3630
Ji     3610
JT     3593
cy     3580
pT     3513
Rj     3508
ok     3496
zc     3490
fe     3402
RT     3391
CU     3338
IA     3302
LS     3231
us     3192
cR     3166
Ay     3150
Ty     3112
lA     3098
eN     3090
QV     3038
TH     3012
cY     3007
TP     2944
Rv     2923
Tz     2868
Mq     2863
Yi     2808
SS     2793
CN     2773
dp     2753
jp     2611
Kq     2554
Iq     2510
AW     2477
yK     2393
iS     2390
OM     2365
BL     2330
al     2271
ht     2271
Ox     2261
zp     2186
HF     2129
XU     2118
gK     2081
Re     2079
gt     1999
xF     1970
sF     1904
Sk     1890
gj     1824
xB     1791
kv     1790
iv     1787
ze     1764
gL     1730
Wr     1727
cg     1708
pZ     1707
mP     1690
aA     1605
uZ     1583
ne     1523
MU     1467
lR     1376
Oe     1358
mX     1302
Ro     1287
fO     1264
kB     1192
wU     1178
FH     1164
sY     1116
zf     1082
Io     1066
uP     1046
In     1038
ja     1035
Yr      862
Tg      814
RB      800
pl      758
tT      749
Dn      656
HO      606
Qm      595
NT      583
uI      528
WC      493
BX      482
Yb      476
FB      433
PG      345
nf      345
wJ      341
fF      335
kP      331
ur      319
uW      269
MF      256
SL      249
Cn      236
XI      198
MX      196
vw      189
gV      124
vQ      120
eA       91
Zv       87
Name: ord_5, dtype: int64